import { useState, useEffect, useRef, useCallback } from "react";

const PAGES=[{id:"chat",name:"Global Chat",emoji:"🌐",grad:"linear-gradient(135deg,#6c5ce7,#a855f7)"},{id:"dm",name:"Messages Privés",emoji:"💬",grad:"linear-gradient(135deg,#4facfe,#00f2fe)",unread:5},{id:"otaku",name:"Otaku",emoji:"🎌",grad:"linear-gradient(135deg,#f093fb,#f5576c)"},{id:"loup-garou",name:"Loup-Garou",emoji:"🐺",grad:"linear-gradient(135deg,#43e97b,#38f9d7)"}];
const AC=["linear-gradient(135deg,#6c5ce7,#a855f7)","linear-gradient(135deg,#f093fb,#f5576c)","linear-gradient(135deg,#4facfe,#00f2fe)","linear-gradient(135deg,#43e97b,#38f9d7)","linear-gradient(135deg,#fa709a,#fee140)","linear-gradient(135deg,#a18cd1,#fbc2eb)","linear-gradient(135deg,#fccb90,#d57eeb)","linear-gradient(135deg,#ff9a9e,#fecfef)","linear-gradient(135deg,#a1c4fd,#c2e9fb)","linear-gradient(135deg,#d4fc79,#96e6a1)","linear-gradient(135deg,#84fab0,#8fd3f4)","linear-gradient(135deg,#ffecd2,#fcb69f)"];
const ROLES={loup:{name:"Loup-Garou",emoji:"🐺",team:"loups",desc:"Éliminez les villageois.",color:"#ef4444"},villageois:{name:"Villageois",emoji:"🧑‍🌾",team:"village",desc:"Trouvez les loups.",color:"#22c55e"},voyante:{name:"Voyante",emoji:"🔮",team:"village",desc:"Voir un rôle chaque nuit.",color:"#a855f7"},sorciere:{name:"Sorcière",emoji:"🧪",team:"village",desc:"Potion vie + mort.",color:"#06b6d4"},chasseur:{name:"Chasseur",emoji:"🏹",team:"village",desc:"Tire en mourant.",color:"#f59e0b"}};
const BOTS=["Luna","Fenrir","Artemis","Shadow","Raven","Storm","Blaze","Mystic","Sage","Ghost","Viper","Phoenix"];
const TM={"role-reveal":8,night:15,"night-result":6,day:30,vote:20,"vote-result":5};
const EMS=["😀","😂","😎","🥺","😭","💀","🤡","😈","🤯","👍","👎","❤️","🔥","⭐","💎","🎉","🚀","⚡"];
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
const assignR=p=>{const n=p.length,r=[];const lc=n<=6?1:n<=9?2:3;for(let i=0;i<lc;i++)r.push("loup");if(n>=5)r.push("voyante");if(n>=6)r.push("sorciere");if(n>=8)r.push("chasseur");while(r.length<n)r.push("villageois");const s=shuffle(r);return p.map((x,i)=>({...x,role:s[i],team:ROLES[s[i]].team}));};
const chkW=p=>{const a=p.filter(x=>x.alive);const l=a.filter(x=>x.team==="loups").length;const v=a.filter(x=>x.team==="village").length;if(!l)return"village";if(l>=v)return"loups";return null;};
const Av=({name,color,size=36,alive=true,emoji})=>(<div style={{position:"relative",flexShrink:0}}><div style={{width:size,height:size,borderRadius:size>30?12:10,background:color,display:"flex",alignItems:"center",justifyContent:"center",fontSize:emoji?size*.45:size*.4,fontWeight:700,color:"#fff",opacity:alive?1:.3,filter:alive?"none":"grayscale(1)"}}>{emoji||name[0].toUpperCase()}</div>{!alive&&<div style={{position:"absolute",top:-2,right:-2,fontSize:size*.3}}>💀</div>}</div>);

/* ===== GLOBAL CHAT ===== */
function GChat({t}){
  const ME={id:"u1",name:"DINO",color:AC[0]};
  const[msgs,setMsgs]=useState([{id:"1",uid:"u2",name:"Alex",color:AC[1],content:"Yo tout le monde! 🔥",reply:null,reactions:[],time:Date.now()-300000},{id:"2",uid:"u3",name:"Sophie",color:AC[2],content:"Quelqu'un a lu Solo Leveling?",reply:null,reactions:[{emoji:"🔥",count:5,mine:false}],time:Date.now()-240000},{id:"3",uid:"u4",name:"Jean",color:AC[3],content:"@alex le plot twist!! 🤯",reply:null,reactions:[],time:Date.now()-180000},{id:"4",uid:"u1",name:"DINO",color:AC[0],content:"Ce site est trop bien 💯",reply:null,reactions:[{emoji:"❤️",count:8,mine:true}],time:Date.now()-120000},{id:"5",uid:"u2",name:"Alex",color:AC[1],content:"Merci! 😎",reply:{author:"DINO",content:"Ce site est trop bien 💯"},reactions:[],time:Date.now()-60000},{id:"6",uid:"u5",name:"Marie",color:AC[4],content:"Sa k ap fèt? 🇭🇹",reply:null,reactions:[],time:Date.now()-30000}]);
  const[inp,setInp]=useState("");const[reply,setReply]=useState(null);const[hov,setHov]=useState(null);const[showE,setShowE]=useState(false);const ref=useRef(null);const iref=useRef(null);
  useEffect(()=>{ref.current?.scrollIntoView({behavior:"smooth"});},[msgs]);
  const send=()=>{if(!inp.trim())return;setMsgs(p=>[...p,{id:`m${Date.now()}`,uid:ME.id,name:ME.name,color:ME.color,content:inp,reply:reply?{author:reply.name,content:reply.content}:null,reactions:[],time:Date.now()}]);setInp("");setReply(null);};
  const react=(mid,em)=>{setMsgs(p=>p.map(m=>{if(m.id!==mid)return m;const ex=m.reactions.find(r=>r.emoji===em);if(ex)return{...m,reactions:ex.mine?(ex.count===1?m.reactions.filter(r=>r.emoji!==em):m.reactions.map(r=>r.emoji===em?{...r,count:r.count-1,mine:false}:r)):m.reactions.map(r=>r.emoji===em?{...r,count:r.count+1,mine:true}:r)};return{...m,reactions:[...m.reactions,{emoji:em,count:1,mine:true}]};}));};
  const fmt=ts=>new Date(ts).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});
  return(<div style={{flex:1,display:"flex",flexDirection:"column"}}>
    <div style={{padding:"14px 20px",borderBottom:`1px solid ${t.bd}`,background:t.bg2,display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:20}}>🌐</span><div><div style={{fontWeight:700,fontSize:15}}>Global Chat</div><div style={{fontSize:11,color:t.tm}}>1,247 en ligne</div></div></div>
    <div style={{flex:1,overflowY:"auto",padding:"12px 20px",display:"flex",flexDirection:"column",gap:2}}>
      {msgs.map((m,i)=>{const sa=i===0||msgs[i-1]?.uid!==m.uid;const own=m.uid===ME.id;const h=hov===m.id;return(<div key={m.id} onMouseEnter={()=>setHov(m.id)} onMouseLeave={()=>setHov(null)} style={{display:"flex",gap:10,padding:"3px 8px",marginTop:sa?10:0,borderRadius:8,background:h?t.bgM:"transparent",position:"relative"}}>
        <div style={{width:36,flexShrink:0}}>{sa&&<Av name={m.name} color={m.color} size={36}/>}</div>
        <div style={{flex:1,minWidth:0}}>
          {sa&&<div style={{display:"flex",alignItems:"baseline",gap:8,marginBottom:2}}><span style={{fontWeight:600,fontSize:13,color:own?t.ac:t.t1}}>{m.name}</span><span style={{fontSize:10,color:t.tm}}>{fmt(m.time)}</span></div>}
          {m.reply&&<div style={{display:"flex",alignItems:"center",gap:6,padding:"3px 10px",marginBottom:3,borderLeft:`3px solid ${t.ac}`,background:t.acs,borderRadius:"0 6px 6px 0",fontSize:12,color:t.t2}}><span style={{fontWeight:600}}>@{m.reply.author}</span><span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{m.reply.content}</span></div>}
          <div style={{fontSize:14,lineHeight:1.5,wordBreak:"break-word"}}>{m.content.split(/(@\w+)/g).map((p,j)=>p.startsWith("@")?<span key={j} style={{background:t.acs,color:t.ac,borderRadius:4,padding:"1px 4px",fontWeight:500}}>{p}</span>:p)}</div>
          {m.reactions.length>0&&<div style={{display:"flex",gap:4,marginTop:5}}>{m.reactions.map(r=><button key={r.emoji} onClick={()=>react(m.id,r.emoji)} style={{display:"flex",alignItems:"center",gap:4,padding:"2px 8px",borderRadius:20,fontSize:12,fontFamily:"inherit",border:`1px solid ${r.mine?t.ac:t.bd}`,background:r.mine?t.acs:"transparent",color:t.t1,cursor:"pointer"}}><span>{r.emoji}</span><span style={{fontSize:11,fontWeight:600}}>{r.count}</span></button>)}</div>}
        </div>
        {h&&<div style={{position:"absolute",top:-12,right:8,display:"flex",gap:1,background:t.bg3,border:`1px solid ${t.bd}`,borderRadius:8,padding:2,boxShadow:"0 4px 16px rgba(0,0,0,.3)",zIndex:10}}>{["😀","❤️","👍"].map(e=><button key={e} onClick={()=>react(m.id,e)} style={{background:"transparent",border:"none",cursor:"pointer",fontSize:14,padding:"3px 5px",borderRadius:4}}>{e}</button>)}<div style={{width:1,background:t.bd,margin:"3px 1px"}}/><button onClick={()=>{setReply(m);iref.current?.focus();}} style={{background:"transparent",border:"none",cursor:"pointer",fontSize:12,padding:"3px 5px",color:t.tm}}>↩️</button></div>}
      </div>);})}
      <div ref={ref}/></div>
    <div style={{borderTop:`1px solid ${t.bd}`,background:t.bg2}}>
      {reply&&<div style={{padding:"8px 20px",display:"flex",alignItems:"center",gap:8,background:t.acs,borderBottom:`1px solid ${t.bd}`}}><div style={{width:3,height:20,background:t.ac,borderRadius:2}}/><div style={{flex:1}}><div style={{fontSize:11,fontWeight:600,color:t.ac}}>↩ @{reply.name}</div><div style={{fontSize:12,color:t.t2,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{reply.content}</div></div><button onClick={()=>setReply(null)} style={{background:"transparent",border:"none",cursor:"pointer",color:t.tm,fontSize:14}}>✕</button></div>}
      {showE&&<div style={{padding:"10px 20px",borderBottom:`1px solid ${t.bd}`,display:"flex",flexWrap:"wrap",gap:2}}>{EMS.map(em=><button key={em} onClick={()=>{setInp(p=>p+em);iref.current?.focus();}} style={{background:"transparent",border:"none",cursor:"pointer",fontSize:20,padding:3,borderRadius:6}}>{em}</button>)}</div>}
      <div style={{padding:"12px 20px",display:"flex",alignItems:"center",gap:8}}>
        <button onClick={()=>setShowE(!showE)} style={{background:showE?t.acs:"transparent",border:"none",cursor:"pointer",fontSize:18,padding:5,borderRadius:8,color:showE?t.ac:t.tm}}>😀</button>
        <div style={{flex:1,background:t.bg3,border:`1px solid ${t.bi}`,borderRadius:12,display:"flex",padding:"0 12px"}}><input ref={iref} value={inp} onChange={e=>setInp(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Message #Global Chat..." style={{flex:1,background:"transparent",border:"none",outline:"none",color:t.t1,fontSize:14,padding:"10px 0",fontFamily:"inherit"}}/></div>
        <button onClick={send} disabled={!inp.trim()} style={{background:inp.trim()?t.ac:t.bg3,border:"none",borderRadius:10,color:inp.trim()?"#fff":t.tm,padding:"10px 14px",fontSize:15,cursor:inp.trim()?"pointer":"default"}}>➤</button>
      </div>
    </div>
  </div>);
}

/* ===== PRIVATE MESSAGES ===== */
function DMs({t}){
  const CONVOS=[{id:"dm1",name:"Alex",color:AC[1],status:"online",last:"T'as vu le nouveau chapitre?",unread:2},{id:"dm2",name:"Sophie",color:AC[2],status:"online",last:"Le bug est fixé 🎉",unread:0},{id:"dm3",name:"Jean",color:AC[3],status:"away",last:"Ki lè ou disponib?",unread:3},{id:"dm4",name:"Marie",color:AC[4],status:"offline",last:"Merci pour l'aide!",unread:0}];
  const INIT={dm1:[{s:"other",c:"Yo! T'as vu JJK?",t:"14:30"},{s:"me",c:"Ouiii c'était fou! 🔥",t:"14:32"},{s:"other",c:"Le twist j'étais choqué",t:"14:33"},{s:"me",c:"Vivement la suite",t:"14:35"}],dm2:[{s:"other",c:"Le bug chat est fixé",t:"16:10"},{s:"me",c:"Nice merci! 🙏",t:"16:12"},{s:"other",c:"C'était un pb de state 🎉",t:"16:13"}],dm3:[{s:"other",c:"Salut DINO!",t:"10:00"},{s:"other",c:"Ki lè ou disponib?",t:"10:01"},{s:"me",c:"Demain après-midi",t:"10:15"}],dm4:[{s:"me",c:"Regarde ce tuto React",t:"09:00"},{s:"other",c:"Merci! Trop utile 💯",t:"09:30"}]};
  const[act,setAct]=useState(null);const[inp,setInp]=useState("");const[all,setAll]=useState(INIT);const ref=useRef(null);
  const conv=CONVOS.find(c=>c.id===act);const msgs=act?(all[act]||[]):[];
  useEffect(()=>{ref.current?.scrollIntoView({behavior:"smooth"});},[msgs,act]);
  const send=()=>{if(!inp.trim()||!act)return;setAll(p=>({...p,[act]:[...(p[act]||[]),{s:"me",c:inp,t:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}]}));setInp("");setTimeout(()=>{const r=["Ok 👍","Ahh je vois","Trop bien!","On en reparle","😂😂","💯","Intéressant..."];setAll(p=>({...p,[act]:[...(p[act]||[]),{s:"other",c:r[Math.floor(Math.random()*r.length)],t:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}]}));},1500+Math.random()*2000);};
  const sc={online:"#22c55e",away:"#eab308",offline:"#555570"};
  return(<div style={{flex:1,display:"flex"}}>
    <div style={{width:280,borderRight:`1px solid ${t.bd}`,background:t.bg2,display:"flex",flexDirection:"column"}}>
      <div style={{padding:"14px 16px",borderBottom:`1px solid ${t.bd}`}}><div style={{fontWeight:700,fontSize:15}}>💬 Messages Privés</div></div>
      <div style={{flex:1,overflowY:"auto",padding:8}}>{CONVOS.map(c=>(<button key={c.id} onClick={()=>setAct(c.id)} style={{width:"100%",display:"flex",alignItems:"center",gap:10,padding:10,borderRadius:10,border:"none",cursor:"pointer",textAlign:"left",marginBottom:2,background:act===c.id?t.bgA:"transparent",color:t.t1,fontFamily:"inherit",transition:"background .15s"}} onMouseEnter={e=>{if(act!==c.id)e.currentTarget.style.background=t.bgH}} onMouseLeave={e=>{if(act!==c.id)e.currentTarget.style.background="transparent"}}>
        <div style={{position:"relative"}}><Av name={c.name} color={c.color} size={36}/><div style={{position:"absolute",bottom:-1,right:-1,width:10,height:10,borderRadius:"50%",background:sc[c.status],border:`2px solid ${t.bg2}`}}/></div>
        <div style={{flex:1,minWidth:0}}><div style={{fontSize:13,fontWeight:c.unread>0?700:500}}>{c.name}</div><div style={{fontSize:11,color:t.tm,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{c.last}</div></div>
        {c.unread>0&&<div style={{background:t.red,color:"#fff",fontSize:10,fontWeight:700,borderRadius:10,padding:"2px 6px",minWidth:18,textAlign:"center"}}>{c.unread}</div>}
      </button>))}</div>
    </div>
    {conv?(<div style={{flex:1,display:"flex",flexDirection:"column"}}>
      <div style={{padding:"14px 20px",borderBottom:`1px solid ${t.bd}`,background:t.bg2,display:"flex",alignItems:"center",gap:10}}><Av name={conv.name} color={conv.color} size={32}/><div><div style={{fontWeight:600,fontSize:14}}>{conv.name}</div><div style={{fontSize:11,color:t.tm,display:"flex",alignItems:"center",gap:4}}><div style={{width:6,height:6,borderRadius:"50%",background:sc[conv.status]}}/>{conv.status}</div></div></div>
      <div style={{flex:1,overflowY:"auto",padding:"16px 20px",display:"flex",flexDirection:"column",gap:8}}>
        {msgs.map((m,i)=>(<div key={i} style={{display:"flex",justifyContent:m.s==="me"?"flex-end":"flex-start",animation:"fadeIn .2s"}}><div style={{maxWidth:"70%",padding:"10px 14px",borderRadius:16,fontSize:13,lineHeight:1.5,background:m.s==="me"?t.ac:t.bg3,color:m.s==="me"?"#fff":t.t1,borderBottomRightRadius:m.s==="me"?4:16,borderBottomLeftRadius:m.s==="me"?16:4}}>{m.c}<div style={{fontSize:10,opacity:.6,marginTop:4,textAlign:"right"}}>{m.t}</div></div></div>))}
        <div ref={ref}/></div>
      <div style={{padding:"12px 20px",borderTop:`1px solid ${t.bd}`,background:t.bg2,display:"flex",gap:8}}>
        <div style={{flex:1,background:t.bg3,border:`1px solid ${t.bi}`,borderRadius:12,display:"flex",padding:"0 12px"}}><input value={inp} onChange={e=>setInp(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder={`Message @${conv.name}...`} style={{flex:1,background:"transparent",border:"none",outline:"none",color:t.t1,fontSize:13,padding:"10px 0",fontFamily:"inherit"}}/></div>
        <button onClick={send} disabled={!inp.trim()} style={{background:inp.trim()?t.ac:t.bg3,border:"none",borderRadius:10,color:inp.trim()?"#fff":t.tm,padding:"10px 14px",fontSize:15,cursor:inp.trim()?"pointer":"default"}}>➤</button>
      </div>
    </div>):(<div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column",gap:8}}><span style={{fontSize:40}}>💬</span><span style={{color:t.t2,fontSize:14}}>Sélectionnez une conversation</span></div>)}
  </div>);
}

/* ===== OTAKU ===== */
function Otaku({t}){
  const TABS=[{id:"manga",l:"Manga",e:"📖"},{id:"anime",l:"Anime",e:"🎬"},{id:"webtoon",l:"Webtoon",e:"📱"},{id:"ln",l:"Light Novel",e:"📚"}];
  const D={manga:[{title:"Solo Leveling",icon:"⚔️",ch:201,st:"Terminé",r:4.8,g:"Action"},{title:"Jujutsu Kaisen",icon:"👹",ch:271,st:"Terminé",r:4.7,g:"Shonen"},{title:"One Piece",icon:"🏴‍☠️",ch:1120,st:"En cours",r:4.9,g:"Aventure"},{title:"Chainsaw Man",icon:"🪚",ch:180,st:"En cours",r:4.6,g:"Dark Fantasy"},{title:"Spy x Family",icon:"🕵️",ch:103,st:"En cours",r:4.7,g:"Comédie"},{title:"Blue Lock",icon:"⚽",ch:275,st:"En cours",r:4.5,g:"Sport"},{title:"Kaiju No.8",icon:"🦎",ch:113,st:"En cours",r:4.5,g:"Action"},{title:"Dandadan",icon:"👻",ch:170,st:"En cours",r:4.6,g:"Action"}],anime:[{title:"Demon Slayer S4",icon:"🔥",ch:12,st:"En cours",r:4.8,g:"Action"},{title:"Attack on Titan",icon:"🗡️",ch:87,st:"Terminé",r:4.9,g:"Dark Fantasy"},{title:"Frieren",icon:"🧝",ch:28,st:"En cours",r:4.9,g:"Fantasy"},{title:"Vinland Saga",icon:"⚔️",ch:24,st:"Terminé",r:4.8,g:"Aventure"},{title:"Oshi no Ko",icon:"⭐",ch:13,st:"Terminé",r:4.5,g:"Drame"}],webtoon:[{title:"Tower of God",icon:"🗼",ch:600,st:"En cours",r:4.7,g:"Fantasy"},{title:"Omniscient Reader",icon:"📖",ch:180,st:"En cours",r:4.8,g:"Fantasy"},{title:"TBATE",icon:"👑",ch:200,st:"En cours",r:4.6,g:"Fantasy"},{title:"Eleceed",icon:"⚡",ch:300,st:"En cours",r:4.7,g:"Action"},{title:"Lookism",icon:"👤",ch:490,st:"En cours",r:4.5,g:"Action"}],ln:[{title:"Mushoku Tensei",icon:"🌍",ch:26,st:"Terminé",r:4.7,g:"Isekai"},{title:"Re:Zero",icon:"🔄",ch:37,st:"En cours",r:4.6,g:"Fantasy"},{title:"SAO",icon:"⚔️",ch:27,st:"Terminé",r:4.3,g:"Sci-Fi"},{title:"Overlord",icon:"💀",ch:16,st:"En cours",r:4.5,g:"Fantasy"}]};
  const[tab,setTab]=useState("manga");const[search,setSearch]=useState("");
  const items=D[tab].filter(x=>x.title.toLowerCase().includes(search.toLowerCase()));
  return(<div style={{flex:1,display:"flex",flexDirection:"column"}}>
    <div style={{padding:"14px 20px",borderBottom:`1px solid ${t.bd}`,background:t.bg2}}>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:12}}>
        <div style={{fontWeight:700,fontSize:15,display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:20}}>🎌</span>Otaku</div>
        <div style={{background:t.bg3,borderRadius:10,padding:"6px 12px",display:"flex",alignItems:"center",gap:6,width:180}}><span style={{fontSize:12}}>🔍</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher..." style={{background:"transparent",border:"none",outline:"none",color:t.t1,fontSize:12,width:"100%",fontFamily:"inherit"}}/></div>
      </div>
      <div style={{display:"flex",gap:4}}>{TABS.map(tb=><button key={tb.id} onClick={()=>setTab(tb.id)} style={{padding:"6px 14px",borderRadius:20,border:"none",cursor:"pointer",fontSize:12,fontWeight:600,fontFamily:"inherit",background:tab===tb.id?t.ac:t.bg3,color:tab===tb.id?"#fff":t.t2}}>{tb.e} {tb.l}</button>)}</div>
    </div>
    <div style={{flex:1,overflowY:"auto",padding:20}}>
      {!items.length?<div style={{textAlign:"center",padding:40,color:t.t2}}><div style={{fontSize:32,marginBottom:8}}>🔍</div>Aucun résultat</div>:
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(160px,1fr))",gap:14}}>
        {items.map((x,i)=><div key={i} style={{background:t.bg3,borderRadius:14,overflow:"hidden",border:`1px solid ${t.bd}`,cursor:"pointer",transition:"transform .2s,box-shadow .2s"}} onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-4px)";e.currentTarget.style.boxShadow="0 8px 24px rgba(0,0,0,.3)";}} onMouseLeave={e=>{e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.boxShadow="none";}}>
          <div style={{height:140,background:AC[i%AC.length],display:"flex",alignItems:"center",justifyContent:"center",fontSize:40}}>{x.icon}</div>
          <div style={{padding:"10px 12px"}}>
            <div style={{fontSize:13,fontWeight:700,marginBottom:4,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{x.title}</div>
            <div style={{display:"flex",alignItems:"center",gap:6,fontSize:11,color:t.t2}}>⭐ {x.r} • {x.ch} ch.</div>
            <div style={{display:"flex",gap:4,marginTop:6}}>
              <span style={{fontSize:10,padding:"2px 8px",borderRadius:10,fontWeight:600,background:x.st==="En cours"?"rgba(34,197,94,.12)":"rgba(108,92,231,.12)",color:x.st==="En cours"?"#22c55e":"#a855f7"}}>{x.st}</span>
              <span style={{fontSize:10,padding:"2px 8px",borderRadius:10,background:t.bgH||t.bg3,color:t.t2}}>{x.g}</span>
            </div>
          </div>
        </div>)}
      </div>}
    </div>
  </div>);
}

/* ===== LOUP-GAROU ===== */
function LG({t}){
  const PID="me",PN="DINO";
  const init=()=>({ph:"lobby",rnd:0,pl:[{id:PID,name:PN,color:AC[0],alive:true,bot:false}],ms:[{id:"s0",c:"🐺 Bienvenue!",tp:"system",time:Date.now()}],tmr:0,mxT:0,nt:null,vt:null,voyt:null,hu:false,ku:false,ht:null,kt:null,win:null});
  const[g,setG]=useState(init);const[inp,setInp]=useState("");const[cnt,setCnt]=useState(6);const[vR,setVR]=useState(null);const[hunt,setHunt]=useState(false);
  const tR=useRef(null);const cR=useRef(null);const me=g.pl.find(p=>p.id===PID);
  useEffect(()=>{cR.current?.scrollIntoView({behavior:"smooth"});},[g.ms]);
  useEffect(()=>{if(g.tmr>0&&g.ph!=="lobby"){tR.current=setTimeout(()=>setG(p=>({...p,tmr:p.tmr-1})),1000);}else if(g.tmr===0&&g.ph!=="lobby"&&g.ph!=="end"){pe();}return()=>clearTimeout(tR.current);},[g.tmr,g.ph]);
  const am=useCallback((c,tp="system",s=null,sn=null)=>{setG(p=>({...p,ms:[...p.ms,{id:`m${Date.now()}${Math.random()}`,c,tp,s,sn,time:Date.now()}]}));},[]);
  const go=()=>{const ns=shuffle(BOTS);const bots=Array.from({length:cnt-1},(_,i)=>({id:`b${i}`,name:ns[i],color:AC[(i+1)%AC.length],alive:true,bot:true}));const all=assignR([g.pl[0],...bots]);setG(p=>({...p,pl:all,ph:"role-reveal",rnd:1,tmr:TM["role-reveal"],mxT:TM["role-reveal"]}));};
  const goN=()=>{setVR(null);am(`🌙 Nuit ${g.rnd}...`);setG(p=>({...p,ph:"night",tmr:TM.night,mxT:TM.night,nt:null,voyt:null,ht:null,kt:null}));};
  const nr=()=>{const al=g.pl.filter(p=>p.alive);const vi=al.filter(p=>p.team==="village");let wt=g.nt||(vi.length?vi[Math.floor(Math.random()*vi.length)].id:null);let k=wt?[wt]:[];if(me?.role==="voyante"&&me.alive&&g.voyt){const tg=g.pl.find(p=>p.id===g.voyt);if(tg)setVR({name:tg.name,role:tg.role});}const so=g.pl.find(p=>p.role==="sorciere"&&p.alive);if(so?.bot){if(!g.hu&&wt&&Math.random()>.5)k=k.filter(id=>id!==wt);if(!g.ku&&Math.random()>.7){const t2=al.filter(p=>p.team!=="loups"&&p.role!=="sorciere");if(t2.length)k.push(t2[Math.floor(Math.random()*t2.length)].id);}}else if(so&&!so.bot){if(g.ht&&wt)k=k.filter(id=>id!==wt);if(g.kt)k.push(g.kt);}k=[...new Set(k)];const kp=g.pl.filter(p=>k.includes(p.id));setG(p=>({...p,ph:"night-result",tmr:TM["night-result"],mxT:TM["night-result"],pl:p.pl.map(pl=>k.includes(pl.id)?{...pl,alive:false}:pl)}));if(!kp.length)am("☀️ Personne tué!");else kp.forEach(p=>am(`💀 ${p.name} dévoré(e)... ${ROLES[p.role].emoji} ${ROLES[p.role].name}`,"kill"));};
  const goV=()=>{am("🗳️ Votez!");setG(p=>({...p,ph:"vote",tmr:TM.vote,mxT:TM.vote,vt:null}));};
  const vr=()=>{const al=g.pl.filter(p=>p.alive);const vo={};al.forEach(p=>{if(p.bot){const o=al.filter(v=>v.id!==p.id);const w=o.flatMap(v=>v.team==="loups"?[v,v]:[v]);const tg=p.team==="loups"?al.filter(v=>v.team==="village")[Math.floor(Math.random()*al.filter(v=>v.team==="village").length)]?.id:w[Math.floor(Math.random()*w.length)]?.id;if(tg)vo[tg]=(vo[tg]||0)+1;}});if(g.vt&&me?.alive)vo[g.vt]=(vo[g.vt]||0)+1;let mx=0,el=null;Object.entries(vo).forEach(([id,c])=>{if(c>mx){mx=c;el=id;}});if(el){const p=g.pl.find(pl=>pl.id===el);am(`⚖️ ${p.name} éliminé(e) (${mx} votes)!`,"vote");am(`${ROLES[p.role].emoji} ${p.name} était ${ROLES[p.role].name}`,"reveal");setG(pr=>({...pr,ph:"vote-result",tmr:TM["vote-result"],mxT:TM["vote-result"],pl:pr.pl.map(pl=>pl.id===el?{...pl,alive:false}:pl)}));if(p.role==="chasseur"){if(p.id===PID)setHunt(true);else{const tg=g.pl.filter(pl=>pl.alive&&pl.id!==el);if(tg.length){const sh=tg[Math.floor(Math.random()*tg.length)];am(`🏹 ${p.name} tire sur ${sh.name}!`,"kill");setG(pr=>({...pr,pl:pr.pl.map(pl=>pl.id===sh.id?{...pl,alive:false}:pl)}));}}}}};
  const endG=w=>{am(`${w==="loups"?"🐺 Loups":"🏡 Village"} gagnent! 🎉`);setG(p=>({...p,ph:"end",win:w,tmr:0}));};
  const pe=()=>{switch(g.ph){case"role-reveal":goN();break;case"night":nr();break;case"night-result":{const w=chkW(g.pl);if(w)endG(w);else{am("☀️ Discutez!");setG(p=>({...p,ph:"day",tmr:TM.day,mxT:TM.day}));}break;}case"day":goV();break;case"vote":vr();break;case"vote-result":{const w=chkW(g.pl);if(w)endG(w);else{setG(p=>({...p,rnd:p.rnd+1}));setTimeout(goN,500);}break;}}};
  const chat=()=>{if(!inp.trim()||!me?.alive)return;if(g.ph==="night"&&me.team!=="loups")return;am(inp,"chat",PID,PN);setInp("");if(Math.random()>.6){const bot=g.pl.filter(p=>p.bot&&p.alive)[0];if(bot){const r=["Hmm 🤔","Ok 👍","Louche 😒","Qui a pas parlé? 👀","Confiance à personne"];setTimeout(()=>am(r[Math.floor(Math.random()*r.length)],"chat",bot.id,bot.name),1500);}}};
  const al=g.pl.filter(p=>p.alive),de=g.pl.filter(p=>!p.alive);const isL=me?.team==="loups",isV=me?.role==="voyante",isS=me?.role==="sorciere",isN=g.ph==="night";
  const cl=p=>{if(g.ph==="vote"&&p.id!==PID&&me?.alive)setG(pr=>({...pr,vt:p.id}));if(isN&&isL&&me?.alive&&p.team!=="loups")setG(pr=>({...pr,nt:p.id}));if(isN&&isV&&me?.alive&&p.id!==PID)setG(pr=>({...pr,voyt:p.id}));if(hunt&&p.id!==PID&&p.alive){am(`🏹 ${PN} tire sur ${p.name}!`,"kill");setG(pr=>({...pr,pl:pr.pl.map(pl=>pl.id===p.id?{...pl,alive:false}:pl)}));setHunt(false);}};
  const pL={lobby:"🏠 Lobby","role-reveal":"🎭 Rôle",night:`🌙 Nuit ${g.rnd}`,"night-result":"🌅 Aube",day:`☀️ Jour ${g.rnd}`,vote:"🗳️ Vote","vote-result":"⚖️ Résultat",end:"🏆 Fin"};
  const pB={lobby:"#667eea","role-reveal":"#f5576c",night:"#302b63","night-result":"#f5af19",day:"#f5af19",vote:"#eb3349","vote-result":"#4b6cb7",end:"#f7971e"};
  return(<div style={{flex:1,display:"flex",background:isN?"linear-gradient(180deg,#0a0a1a,#10101f)":t.bg1,transition:"background 1s"}}>
    <div style={{width:190,background:t.bg2,borderRight:`1px solid ${t.bd}`,display:"flex",flexDirection:"column",flexShrink:0}}>
      <div style={{padding:12,borderBottom:`1px solid ${t.bd}`}}><div style={{fontSize:14,fontWeight:700}}>🐺 Joueurs</div>{g.ph!=="lobby"&&<div style={{fontSize:11,color:t.t2,marginTop:2}}>R{g.rnd} • {al.length} en vie</div>}</div>
      <div style={{flex:1,overflowY:"auto",padding:6}}>
        <div style={{fontSize:10,fontWeight:600,textTransform:"uppercase",letterSpacing:".5px",color:t.tm,padding:"6px 6px 2px"}}>En vie — {al.length}</div>
        {al.map(p=>{const sel=(g.ph==="vote"&&g.vt===p.id)||(isN&&g.nt===p.id);const can=(g.ph==="vote"&&p.id!==PID&&me?.alive)||(isN&&isL&&p.team!=="loups"&&me?.alive)||(isN&&isV&&me?.alive&&p.id!==PID)||hunt;return(<div key={p.id} onClick={()=>cl(p)} style={{display:"flex",alignItems:"center",gap:8,padding:6,borderRadius:8,background:sel?"rgba(239,68,68,.12)":"transparent",cursor:can?"pointer":"default"}}><Av name={p.name} color={p.color} size={28} emoji={(p.id===PID||g.ph==="end"||(isL&&p.team==="loups"))&&p.role?ROLES[p.role].emoji:null}/><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:p.id===PID?700:500,color:p.id===PID?t.ac:t.t1,display:"flex",alignItems:"center",gap:3}}>{p.name}{p.id===PID&&<span style={{fontSize:8,background:t.acs,padding:"1px 4px",borderRadius:3,color:t.ac}}>TOI</span>}</div>{(p.id===PID||g.ph==="end")&&p.role&&<div style={{fontSize:10,color:ROLES[p.role].color}}>{ROLES[p.role].name}</div>}</div></div>);})}
        {de.length>0&&<><div style={{fontSize:10,fontWeight:600,textTransform:"uppercase",letterSpacing:".5px",color:t.tm,padding:"8px 6px 2px"}}>Éliminés — {de.length}</div>{de.map(p=><div key={p.id} style={{display:"flex",alignItems:"center",gap:8,padding:"4px 6px",opacity:.4}}><Av name={p.name} color={p.color} size={24} alive={false} emoji={p.role?ROLES[p.role].emoji:null}/><span style={{fontSize:11,textDecoration:"line-through",color:t.t2}}>{p.name}</span></div>)}</>}
      </div>
    </div>
    <div style={{flex:1,display:"flex",flexDirection:"column",minWidth:0}}>
      <div style={{padding:"10px 20px",borderBottom:`1px solid ${t.bd}`,background:t.bg2,display:"flex",alignItems:"center",gap:12}}><div style={{background:pB[g.ph],padding:"8px 14px",borderRadius:8,color:"#fff",fontWeight:700,fontSize:13}}>{pL[g.ph]}</div><div style={{flex:1}}/>{g.tmr>0&&<div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:22,fontWeight:800,fontFamily:"'Space Grotesk',monospace",color:g.tmr<=5?t.red:t.t1,animation:g.tmr<=5?"pulse .5s infinite":"none"}}>{g.tmr}s</span><div style={{width:60,height:4,background:"rgba(255,255,255,.08)",borderRadius:2,overflow:"hidden"}}><div style={{width:`${(g.tmr/g.mxT)*100}%`,height:"100%",background:g.tmr<=5?t.red:"#6c5ce7",transition:"width 1s linear",borderRadius:2}}/></div></div>}{g.ph==="end"&&<button onClick={()=>{setG(init());setVR(null);setHunt(false);}} style={{background:t.ac,border:"none",borderRadius:8,color:"#fff",padding:"8px 14px",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>🔄 Rejouer</button>}</div>
      {g.ph==="lobby"&&<div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column",gap:20,animation:"fadeIn .5s"}}><div style={{fontSize:50,animation:"float 3s ease-in-out infinite"}}>🐺</div><div style={{textAlign:"center"}}><div style={{fontSize:22,fontWeight:800}}>Loup-Garou</div><div style={{color:t.t2,fontSize:13}}>Trouvez les loups!</div></div><div style={{background:t.bg3,borderRadius:14,padding:20,width:"100%",maxWidth:300,border:`1px solid ${t.bd}`}}><div style={{fontSize:13,fontWeight:600,marginBottom:8}}>Joueurs</div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><input type="range" min={4} max={12} value={cnt} onChange={e=>setCnt(+e.target.value)} style={{flex:1,accentColor:t.ac}}/><span style={{fontSize:20,fontWeight:800,fontFamily:"'Space Grotesk',monospace",color:t.ac}}>{cnt}</span></div><div style={{display:"flex",flexWrap:"wrap",gap:4,marginBottom:14}}>{(()=>{const r=[],lc=cnt<=6?1:cnt<=9?2:3;r.push({r:"loup",c:lc});if(cnt>=5)r.push({r:"voyante",c:1});if(cnt>=6)r.push({r:"sorciere",c:1});if(cnt>=8)r.push({r:"chasseur",c:1});r.push({r:"villageois",c:cnt-r.reduce((s,x)=>s+x.c,0)});return r.map(x=><span key={x.r} style={{background:`${ROLES[x.r].color}20`,color:ROLES[x.r].color,padding:"3px 8px",borderRadius:14,fontSize:10,fontWeight:600}}>{ROLES[x.r].emoji} ×{x.c}</span>);})()}</div><button onClick={go} style={{width:"100%",padding:12,background:"linear-gradient(135deg,#6c5ce7,#a855f7)",border:"none",borderRadius:10,color:"#fff",fontSize:14,fontWeight:700,cursor:"pointer",fontFamily:"inherit",boxShadow:"0 4px 16px rgba(108,92,231,.4)"}}>🎮 Jouer</button></div></div>}
      {g.ph==="role-reveal"&&me?.role&&<div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",animation:"bounceIn .6s"}}><div style={{background:`linear-gradient(135deg,${ROLES[me.role].color}18,${t.bg3})`,border:`2px solid ${ROLES[me.role].color}40`,borderRadius:20,padding:"30px 36px",textAlign:"center",maxWidth:320,animation:"glow 2s infinite"}}><div style={{fontSize:56,marginBottom:10}}>{ROLES[me.role].emoji}</div><div style={{fontSize:20,fontWeight:800,color:ROLES[me.role].color,marginBottom:6}}>{ROLES[me.role].name}</div><div style={{fontSize:13,color:t.t2,lineHeight:1.5,marginBottom:10}}>{ROLES[me.role].desc}</div><span style={{background:me.team==="loups"?"rgba(239,68,68,.12)":"rgba(34,197,94,.12)",color:me.team==="loups"?"#ef4444":"#22c55e",padding:"4px 12px",borderRadius:14,fontSize:11,fontWeight:700}}>{me.team==="loups"?"🐺 Loups":"🏡 Village"}</span></div></div>}
      {!["lobby","role-reveal"].includes(g.ph)&&<div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden"}}>
        {isN&&me?.alive&&<div style={{padding:"8px 20px",background:"rgba(108,92,231,.06)",borderBottom:`1px solid ${t.bd}`,fontSize:12,animation:"slideDown .3s"}}>{isL&&<span style={{color:"#ef4444",fontWeight:600}}>🐺 Choisissez une victime {g.nt?`→ ${g.pl.find(p=>p.id===g.nt)?.name}`:""}</span>}{isV&&<span style={{color:"#a855f7",fontWeight:600}}>🔮 Inspectez un joueur {vR?`→ ${vR.name} = ${ROLES[vR.role].emoji}`:""}</span>}{isS&&<div style={{display:"flex",gap:8,alignItems:"center"}}>🧪{!g.hu&&<button onClick={()=>setG(p=>({...p,ht:"auto"}))} style={{background:"rgba(34,197,94,.12)",border:"1px solid rgba(34,197,94,.3)",borderRadius:6,padding:"3px 10px",color:"#22c55e",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>💚 Sauver</button>}{!g.ku&&<button onClick={()=>{const tg=al.filter(p=>p.id!==PID);const r2=tg[Math.floor(Math.random()*tg.length)];if(r2)setG(p=>({...p,kt:r2.id}));}} style={{background:"rgba(239,68,68,.12)",border:"1px solid rgba(239,68,68,.3)",borderRadius:6,padding:"3px 10px",color:"#ef4444",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>☠️ Poison</button>}</div>}{!isL&&!isV&&!isS&&<span style={{color:t.t2}}>😴 Zzz...</span>}</div>}
        {g.ph==="vote"&&me?.alive&&<div style={{padding:"8px 20px",background:"rgba(239,68,68,.06)",borderBottom:`1px solid ${t.bd}`,fontSize:12,color:t.red,fontWeight:600,animation:"slideDown .3s"}}>🗳️ Cliquez un joueur! {g.vt?`→ ${g.pl.find(p=>p.id===g.vt)?.name}`:""}</div>}
        {hunt&&<div style={{padding:"8px 20px",background:"rgba(245,158,11,.08)",borderBottom:`1px solid ${t.bd}`,fontSize:12,color:"#f59e0b",fontWeight:600,animation:"shake .5s"}}>🏹 Tirez!</div>}
        {g.ph==="end"&&g.win&&<div style={{padding:"16px 20px",background:g.win==="loups"?"rgba(239,68,68,.08)":"rgba(34,197,94,.08)",textAlign:"center",animation:"bounceIn .6s"}}><div style={{fontSize:32}}>{g.win==="loups"?"🐺":"🏡"}</div><div style={{fontSize:16,fontWeight:800,color:g.win==="loups"?"#ef4444":"#22c55e"}}>{g.win==="loups"?"Loups gagnent!":"Village gagne!"}</div><div style={{fontSize:12,color:t.t2}}>{me?.team===g.win?"🎉 Victoire!":"😔 Défaite..."}</div></div>}
        <div style={{flex:1,overflowY:"auto",padding:"10px 20px",display:"flex",flexDirection:"column",gap:3}}>{g.ms.map(m=><div key={m.id} style={{animation:"fadeIn .2s"}}>{m.tp==="system"&&<div style={{fontSize:12,color:t.t2,padding:"4px 10px",background:t.bg3,borderRadius:6,textAlign:"center"}}>{m.c}</div>}{m.tp==="kill"&&<div style={{fontSize:12,color:"#ef4444",padding:"4px 10px",background:"rgba(239,68,68,.06)",borderRadius:6,borderLeft:"3px solid #ef4444"}}>{m.c}</div>}{m.tp==="vote"&&<div style={{fontSize:12,color:"#f59e0b",padding:"4px 10px",background:"rgba(245,158,11,.06)",borderRadius:6,borderLeft:"3px solid #f59e0b"}}>{m.c}</div>}{m.tp==="reveal"&&<div style={{fontSize:12,color:"#a855f7",padding:"4px 10px",background:"rgba(168,85,247,.06)",borderRadius:6,borderLeft:"3px solid #a855f7"}}>{m.c}</div>}{m.tp==="chat"&&<div style={{display:"flex",gap:6,fontSize:13}}><span style={{fontWeight:700,color:m.s===PID?t.ac:t.t1,flexShrink:0}}>{m.sn}:</span><span>{m.c}</span></div>}</div>)}<div ref={cR}/></div>
        {!["lobby","end"].includes(g.ph)&&<div style={{padding:"10px 20px",borderTop:`1px solid ${t.bd}`,background:t.bg2,display:"flex",gap:8}}><input value={inp} onChange={e=>setInp(e.target.value)} onKeyDown={e=>e.key==="Enter"&&chat()} placeholder={!me?.alive?"💀 Mort(e)...":isN&&!isL?"😴 Zzz...":isN?"🐺 Loups...":"Message..."} disabled={!me?.alive||(isN&&!isL)} style={{flex:1,background:t.bg3,border:`1px solid ${t.bd}`,borderRadius:10,padding:"9px 12px",color:t.t1,fontSize:13,outline:"none",fontFamily:"inherit",opacity:(!me?.alive||(isN&&!isL))?.4:1}}/><button onClick={chat} disabled={!inp.trim()} style={{background:inp.trim()?t.ac:t.bg3,border:"none",borderRadius:10,color:inp.trim()?"#fff":t.tm,padding:"9px 14px",fontSize:14,cursor:inp.trim()?"pointer":"default"}}>➤</button></div>}
      </div>}
    </div>
  </div>);
}

/* ===== MAIN ===== */
export default function App(){
  const[page,setPage]=useState("chat");const[theme,setTheme]=useState("dark");
  const t=theme==="dark"?{bg1:"#0c0c14",bg2:"#111119",bg3:"#1a1a25",bgH:"#1f1f2e",bgA:"#262638",bgM:"rgba(255,255,255,.02)",t1:"#e8e8ed",t2:"#8888a0",tm:"#555570",ac:"#6c5ce7",acs:"rgba(108,92,231,.12)",bd:"rgba(255,255,255,.06)",bi:"rgba(255,255,255,.1)",red:"#ef4444"}:{bg1:"#fff",bg2:"#f7f7fa",bg3:"#eeeef3",bgH:"#e8e8ed",bgA:"#dddde5",bgM:"rgba(0,0,0,.02)",t1:"#1a1a2e",t2:"#6b6b80",tm:"#9999aa",ac:"#6c5ce7",acs:"rgba(108,92,231,.1)",bd:"rgba(0,0,0,.07)",bi:"rgba(0,0,0,.12)",red:"#ef4444"};
  return(<div style={{display:"flex",height:"100vh",background:t.bg1,color:t.t1,fontFamily:"'DM Sans',-apple-system,sans-serif",fontSize:14,overflow:"hidden"}}>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=Space+Grotesk:wght@500;700&display=swap" rel="stylesheet"/>
    <div style={{width:260,background:t.bg2,borderRight:`1px solid ${t.bd}`,display:"flex",flexDirection:"column",flexShrink:0}}>
      <div style={{padding:"16px 16px 12px",borderBottom:`1px solid ${t.bd}`}}>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:12}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:30,height:30,borderRadius:10,background:"linear-gradient(135deg,#6c5ce7,#a855f7)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,fontWeight:800,color:"#fff"}}>C</div><span style={{fontWeight:700,fontSize:16,letterSpacing:"-.3px"}}>Comment Live</span></div><button onClick={()=>setTheme(theme==="dark"?"light":"dark")} style={{background:"transparent",border:"none",cursor:"pointer",fontSize:16}}>{theme==="dark"?"☀️":"🌙"}</button></div>
        <div style={{background:t.bg3,borderRadius:10,padding:"8px 12px",display:"flex",alignItems:"center",gap:8}}><span style={{color:t.tm,fontSize:13}}>🔍</span><input placeholder="Rechercher..." style={{background:"transparent",border:"none",outline:"none",color:t.t1,fontSize:13,width:"100%",fontFamily:"inherit"}}/></div>
      </div>
      <div style={{flex:1,overflowY:"auto",padding:8}}>{PAGES.map(p=>{const a=page===p.id;return(<button key={p.id} onClick={()=>setPage(p.id)} style={{width:"100%",display:"flex",alignItems:"center",gap:10,padding:10,borderRadius:10,border:"none",cursor:"pointer",textAlign:"left",marginBottom:2,background:a?t.bgA:"transparent",color:t.t1,fontFamily:"inherit",transition:"background .15s"}} onMouseEnter={e=>{if(!a)e.currentTarget.style.background=t.bgH}} onMouseLeave={e=>{if(!a)e.currentTarget.style.background="transparent"}}><div style={{width:36,height:36,borderRadius:10,background:p.grad,display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,flexShrink:0}}>{p.emoji}</div><span style={{fontSize:13,fontWeight:a?600:500,flex:1}}>{p.name}</span>{p.unread&&p.unread>0&&<div style={{background:t.red,color:"#fff",fontSize:10,fontWeight:700,borderRadius:10,padding:"2px 6px",minWidth:18,textAlign:"center"}}>{p.unread}</div>}</button>);})}</div>
      <div style={{padding:"12px 16px",borderTop:`1px solid ${t.bd}`,display:"flex",alignItems:"center",gap:10}}><Av name="DINO" color={AC[0]} size={32}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600}}>DINO</div><div style={{fontSize:11,color:t.tm}}>@dino</div></div><button style={{background:"transparent",border:"none",cursor:"pointer",color:t.tm,fontSize:14}}>⚙️</button></div>
    </div>
    <div style={{flex:1,display:"flex",flexDirection:"column",minWidth:0}}>{page==="chat"&&<GChat t={t}/>}{page==="dm"&&<DMs t={t}/>}{page==="otaku"&&<Otaku t={t}/>}{page==="loup-garou"&&<LG t={t}/>}</div>
    <style>{`@keyframes fadeIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}@keyframes bounceIn{0%{transform:scale(.3);opacity:0}50%{transform:scale(1.05)}100%{transform:scale(1);opacity:1}}@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}}@keyframes pulse{0%,100%{transform:scale(1)}50%{transform:scale(1.05)}}@keyframes glow{0%,100%{box-shadow:0 0 10px rgba(108,92,231,.3)}50%{box-shadow:0 0 25px rgba(108,92,231,.6)}}@keyframes slideDown{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:translateY(0)}}@keyframes shake{0%,100%{transform:translateX(0)}25%{transform:translateX(-3px)}75%{transform:translateX(3px)}}*{scrollbar-width:thin;scrollbar-color:rgba(255,255,255,.08) transparent}`}</style>
  </div>);
}
